name: Testing Actions across Repositories
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
  end-2-end:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
        - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/RubDevs/actions-experiment/actions/workflows/e2e.yaml/dispatches \
            -d '{"ref":"main","inputs":{"label":"ruben testing"}}'
  end:
    needs: 
      - end-2-end
    runs-on: ubuntu-latest
    steps:
        - run: echo "Finished, status is ${{ job.status }}."