name: Testing Actions across Repositories
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
  end-2-end:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Trigger workflow in another repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: RubDevs
          repo: actions-experiment
          github_token: ${{ secrets.PAT }}
          workflow_file_name: e2e.yaml
          client_payload: '{"ref":"main","inputs":{"label":"ruben testing"}}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
  end:
    needs: 
      - end-2-end
    runs-on: ubuntu-latest
    steps:
        - run: echo "Finished, status is ${{ job.status }}."